<?php
$posts = $block->GetBlog();
?>

<table>
    <tr>
        <th class="blog-id">Id</th>
        <th class="blog-name">Tiêu Đề</th>
        <th>Nội Dung</th>
    </tr>
    <?php
    foreach ($posts as $data){
        echo '<tr>
                    <td>'.$data->getId().'</td>
                    <td>'.$data->getTitle().'</td>
                    <td>'.$data->getDescription().'</td>
                  </tr>';
    }
    ?>
</table>
